# Generated by Django 3.0.7 on 2020-07-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
