# Generated by Django 3.0.7 on 2020-07-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
