# Generated by Django 3.0.7 on 2020-08-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200727_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10),
        ),
    ]
