# Generated by Django 3.1.7 on 2021-05-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200826_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='gender',
        ),
    ]
