# Generated by Django 3.0.7 on 2020-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocate',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
