# Generated by Django 3.0.7 on 2020-07-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_is_taken'),
        ('allocate', '0008_auto_20200728_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room', unique=True),
        ),
    ]
