# Generated by Django 3.0.7 on 2020-08-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0016_auto_20200729_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
