# Generated by Django 3.0.7 on 2020-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20200826_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='phone',
            field=models.CharField(default=112121212, max_length=20),
            preserve_default=False,
        ),
    ]
